dependencies:
- name: demo272
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.16
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: nodey55
  repository: http://jenkins-x-chartmuseum:8080
  version: 1.0.13
- name: nodey56
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
